# Generated by Django 6.1.1 on 2026-09-23 23:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partenaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionAttendue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periode_debut', models.DateField(verbose_name='Début période')),
                ('periode_fin', models.DateField(verbose_name='Fin période')),
                ('date_echeance', models.DateField(verbose_name='Date échéance')),
                ('montant_attendu', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant attendu')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant payé')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PARTIEL', 'Partiel'), ('PAYE', 'Payé'), ('EN_RETARD', 'En retard'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions_attendues', to='partenaires.partenaire')),
            ],
            options={
                'verbose_name': 'Contribution attendue',
                'verbose_name_plural': 'Contributions attendues',
                'ordering': ['-periode_debut'],
                'unique_together': {('partenaire', 'periode_debut', 'periode_fin')},
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=40, unique=True, verbose_name='Référence')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('devise', models.CharField(choices=[('USD', 'USD ($)'), ('CDF', 'CDF (FC)')], default='USD', max_length=5, verbose_name='Devise')),
                ('date_paiement', models.DateField(default=django.utils.timezone.now, verbose_name='Date paiement')),
                ('periode_debut', models.DateField(verbose_name='Début période')),
                ('periode_fin', models.DateField(verbose_name='Fin période')),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('BANQUE', 'Banque'), ('MOBILE_MONEY', 'Mobile Money'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Mode')),
                ('reference_transaction', models.CharField(blank=True, max_length=100, verbose_name='Réf. transaction')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('ANNULE', 'Annulé')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='partenaires.partenaire', verbose_name='Partenaire')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement', '-created_at'],
                'indexes': [models.Index(fields=['reference'], name='finances_pa_referen_9d27b7_idx'), models.Index(fields=['date_paiement'], name='finances_pa_date_pa_3e42ab_idx'), models.Index(fields=['partenaire', 'statut'], name='finances_pa_partena_b834d9_idx')],
            },
        ),
    ]
