# Generated by Django 6.1.1 on 2026-09-23 23:05

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_partenaire', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('postnom', models.CharField(blank=True, max_length=100, verbose_name='Postnom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('type_partenaire', models.CharField(choices=[('PARTICULIER', 'Particulier'), ('ORGANISATION', 'Organisation'), ('ENTREPRISE', 'Entreprise')], default='PARTICULIER', max_length=20, verbose_name='Type')),
                ('date_adhesion', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'adhésion")),
                ('montant_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant contribution')),
                ('frequence', models.CharField(choices=[('MENSUELLE', 'Mensuelle'), ('TRIMESTRIELLE', 'Trimestrielle'), ('SEMESTRIELLE', 'Semestrielle'), ('ANNUELLE', 'Annuelle'), ('PONCTUELLE', 'Ponctuelle')], default='MENSUELLE', max_length=20, verbose_name='Fréquence')),
                ('devise', models.CharField(choices=[('USD', 'USD ($)'), ('CDF', 'CDF (FC)')], default='USD', max_length=5, verbose_name='Devise')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('DESACTIVE', 'Désactivé')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code_partenaire'], name='partenaires_code_pa_063605_idx'), models.Index(fields=['statut'], name='partenaires_statut_e10933_idx')],
            },
        ),
    ]
