# Generated by Django 6.1.1 on 2026-09-23 23:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('DEACTIVATE', 'Désactivation'), ('REACTIVATE', 'Réactivation'), ('CANCEL', 'Annulation'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion')], max_length=20, verbose_name='Action')),
                ('module', models.CharField(max_length=50, verbose_name='Module')),
                ('objet_id', models.CharField(blank=True, max_length=64, verbose_name='Objet ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'Historiques',
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['-date_action'], name='historique__date_ac_41a336_idx'), models.Index(fields=['module'], name='historique__module_6ba651_idx')],
            },
        ),
    ]
